### PR TITLE
Use nodeGroups to determine reward wallet address

### LINKED ISSUE #2273: Skaled fetches block authors from chain config during catchup
**Note**
Not reproduced if the historic node was created before the first committee rotation 

**Preconditions**
Active Fair chain 4 active committee nodes
boot nodes are presented, but not eligible, and do not participate in DKG 
1 Whitelisted IP for passive node 

**Versions:**
skalenetwork/schain:4.1.0-develop.48-mirage
skalenetwork/schain:4.1.0-develop.49-mirage
skalenetwork/schain:4.1.0-develop.48-mirage-historic
skalenetwork/schain:4.1.0-develop.49-mirage-historic

**To Reproduce**
1. Run 3 committee rotation  
2. Init Historic/indexer node from the catchup 
3. Wait for the skaled container to be initialized and create 2 snapshots
4. Check skaled logs and find block authors and compare them with the actual reward wallet addresses from the chain config 

**Expected behavior**
Block author should be taken from the received block, and be as on other Fair nodes
Possible solution - the Schain config should contain all wallet addresses from all committees  (**TBD**)

**Actual state**
Skaled passes the block author with the committee ID as reward wallets from the actual groups, but the boot nodes mined these blocks without any reward wallet addresses.

**Logs**
```
root@QA-historic:~# cat .skale/node_data/schains/fair-qa-beta-2/schain_fair-qa-beta-2.json  | grep reward
                            "rewardWalletAddress": "0x26C7BaE4A42b5c3C820D57454971f5772917fBb8",
                            "rewardWalletAddress": "0xc2A8202eDAdb06d2de017237D1e71D4BE83C2fc8",
                            "rewardWalletAddress": "0x6677C6EDBaE1AfaBfD0B0dD320df8E71d7381E22",
                            "rewardWalletAddress": "0xD75EadD58b56685910C1dB1f71dEA13Cbd74DEEC",
                            "rewardWalletAddress": "0x26C7BaE4A42b5c3C820D57454971f5772917fBb8",
                            "rewardWalletAddress": "0xc2A8202eDAdb06d2de017237D1e71D4BE83C2fc8",
                            "rewardWalletAddress": "0xD75EadD58b56685910C1dB1f71dEA13Cbd74DEEC",
                            "rewardWalletAddress": "0x6677C6EDBaE1AfaBfD0B0dD320df8E71d7381E22",
```

```
2025-09-11 14:55:21.719562   Reward receiver for block 1: 0000000000000000000000000000000000000000 (index 0)
btrfs subvolume snapshot -r /data_dir/28e07f34 /data_dir/snapshots/2
btrfs subvolume snapshot -r /data_dir/prices_9.db /data_dir/snapshots/2
btrfs subvolume snapshot -r /data_dir/blocks_9.db /data_dir/snapshots/2
btrfs subvolume snapshot -r /data_dir/historic_roots /data_dir/snapshots/2
btrfs subvolume snapshot -r /data_dir/historic_state /data_dir/snapshots/2
btrfs --version
btrfs property set -ts -f /data_dir/snapshots/2/28e07f34 ro false
2025-09-11 14:58:23.352069   Reward receiver for block 2: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
btrfs property set -ts -f /data_dir/snapshots/2/prices_9.db ro false
btrfs property set -ts -f /data_dir/snapshots/2/blocks_9.db ro false
2025-09-11 14:58:23.418937   Reward receiver for block 3: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
2025-09-11 14:58:23.432457   Reward receiver for block 4: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
btrfs property set -ts -f /data_dir/snapshots/2/historic_roots ro false
2025-09-11 14:58:23.445271   Reward receiver for block 5: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
btrfs property set -ts -f /data_dir/snapshots/2/historic_state ro false
2025-09-11 14:58:23.455417   Reward receiver for block 6: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.463543   Reward receiver for block 7: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
2025-09-11 14:58:23.473089   Reward receiver for block 8: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
2025-09-11 14:58:23.482806   Reward receiver for block 9: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
2025-09-11 14:58:23.493100   Reward receiver for block 10: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.502459   Reward receiver for block 11: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
2025-09-11 14:58:23.511129   Reward receiver for block 12: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
2025-09-11 14:58:23.522867   Reward receiver for block 13: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
2025-09-11 14:58:23.531760   Reward receiver for block 14: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.540683   Reward receiver for block 15: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
2025-09-11 14:58:23.549714   Reward receiver for block 16: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
btrfs property set -ts -f /data_dir/snapshots/2/28e07f34 ro true
2025-09-11 14:58:23.558551   Reward receiver for block 17: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
btrfs property set -ts -f /data_dir/snapshots/2/prices_9.db ro true
2025-09-11 14:58:23.565724   Reward receiver for block 18: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.580629   Reward receiver for block 19: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
btrfs property set -ts -f /data_dir/snapshots/2/blocks_9.db ro true
2025-09-11 14:58:23.591965   Reward receiver for block 20: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
btrfs property set -ts -f /data_dir/snapshots/2/historic_roots ro true
2025-09-11 14:58:23.602729   Reward receiver for block 21: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
btrfs property set -ts -f /data_dir/snapshots/2/historic_state ro true
2025-09-11 14:58:23.612246   Reward receiver for block 22: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.619992   Reward receiver for block 23: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
2025-09-11 14:58:23.626364   Reward receiver for block 24: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
2025-09-11 14:58:23.632363   Reward receiver for block 25: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
2025-09-11 14:58:23.637934   Reward receiver for block 26: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.643827   Reward receiver for block 27: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
2025-09-11 14:58:23.649963   Reward receiver for block 28: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
2025-09-11 14:58:23.655810   Reward receiver for block 29: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
2025-09-11 14:58:23.662693   Reward receiver for block 30: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.672637   Reward receiver for block 31: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)
2025-09-11 14:58:23.678324   Reward receiver for block 32: 26c7bae4a42b5c3c820d57454971f5772917fbb8 (index 1)
2025-09-11 14:58:23.684070   Reward receiver for block 33: c2a8202edadb06d2de017237d1e71d4be83c2fc8 (index 2)
2025-09-11 14:58:23.689942   Reward receiver for block 34: d75eadd58b56685910c1db1f71dea13cbd74deec (index 3)
2025-09-11 14:58:23.696341   Reward receiver for block 35: 6677c6edbae1afabfd0b0dd320df8e71d7381e22 (index 4)

```

### PR DESCRIPTION
**Pull request by badrogger**
**Changes** 
- Reward wallet address is read from node historic groups instead of committee nodes

**Testing**
- Add unit test
- Tested on local network

**Performance**
- No performance related changes were made

### CODE REVIEW

File: libethcore/ChainOperationParams.h [hunk 1]
```diff
@@ -187,6 +187,7 @@ struct GroupNode {
     u256 id;
     u256 schainIndex;
     std::string publicKey;
+    Address rewardWalletAddress;
```
Comment (DmytroNazarenko) [inline libethcore/ChainOperationParams.h:191]: Should be under ifdef MIRAGE

File: libethereum/ChainParams.cpp [hunk 2]
```diff
@@ -381,10 +381,14 @@ void ChainParams::processSkaleConfigItems( json_spirit::mObject& obj ) {
                 u256 sChainIndex = groupNodeConfObj.at( 0 ).get_uint64();
                 u256 id = groupNodeConfObj.at( 1 ).get_uint64();
                 string publicKey = groupNodeConfObj.at( 2 ).get_str();
+                Address rewardWalletAddress = ZeroAddress;
+                if ( groupNodeConfObj.size() == 4 ) {
+                    rewardWalletAddress = Address( groupNodeConfObj.at( 3 ).get_str() );
+                }
```
Comment (DmytroNazarenko) [inline libethereum/ChainParams.cpp:388]: Should be under ifdef MIRAGE

File: libethereum/ChainParams.cpp [hunk 3]
```diff
@@ -381,10 +381,14 @@ void ChainParams::processSkaleConfigItems( json_spirit::mObject& obj ) {
...
                 if ( publicKey.empty() ) {
                     BOOST_THROW_EXCEPTION( runtime_error( "Empty public key in config" ) );
                 }
-                groupNodes.push_back( { id, sChainIndex, publicKey } );
+                groupNodes.push_back( { id, sChainIndex, publicKey, rewardWalletAddress } );
```
Comment (DmytroNazarenko) [inline libethereum/ChainParams.cpp]: Should be under ifdef MIRAGE

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]

File: libethereum/ChainParams.cpp [hunk 4]
```diff
@@ -947,21 +957,11 @@ CurrentGroup ChainParams::getNewestGroup() const {
...
-    if ( nodeIterator->rewardWalletAddress == ZeroAddress ) {
-        return nodeIterator->owner;
-    } else {
-        return nodeIterator->rewardWalletAddress;
-    }
+Address ChainParams::getNodeBeneficiaryInHistoricGroup(
+    const unsigned _historicGroupIndex, const uint64_t _sChainIndex ) const {
+    // shifting since sChain indices are numbered from 0
+    uint64_t shiftedIndex = _sChainIndex - 1;
+    return getHistoricNodeRewardWalletAddress( _historicGroupIndex, shiftedIndex );
```
Comment (DmytroNazarenko) [inline libethereum/ChainParams.cpp]: Why do we need this method? It doesn’t appear to add any additional logic compared to getHistoricNodeRewardWalletAddress. I propose removing this method and using getHistoricNodeRewardWalletAddress directly.

**Review by olehnikolaiev — DISMISSED** [review]

**Review by DmytroNazarenko — APPROVED** [review]
