### PR TITLE
2305 Increment epoch during catchup

### LINKED ISSUE #2305: Epoch Id doesn't renewed during the catchup BITE transaction on historical passive node
**Versions**
skalenetwork/schain:4.1.0-develop.56-2291-relwithdebinfo-historic

**Preconditions:**
Fair chain 22 nodes in committee
30 active nodes 
Whitelisted and registered historical passive node
Transition delay 1 hour

**Steps to reproduce:**
1. Run 2 committee rotations with the 3-hour interval each
2. Send the BITE transactions expected to fail with `Not enough funds` error 
3. Save the block number with failed tx  - https://testnet-explorer.fair.cloud/block/40156?tab=txs
4. Remove rotated active nodes that are not in the committee
5. Run the next 2 committee rotations with the 3-hour interval each
6. Init historical node from 0 block 
7. check historical passive node sync
 
**Expected state:**
Historical node should cathing up the new blocks without any errors

**Actual state:**
Historical node is stucks on the block number from step 2 

Block with failed transaction 
https://testnet-explorer.fair.cloud/block/40156?tab=txs

**Logs:**

```
2025-10-17 12:24:32.684156   Block sealed #40154 (#33781bf7…)
2025-10-17 12:24:32.684175   Block stats:BN:40153:BTS:1759193214:TXS:3:HDRS:12:LOGS:3520:SENGS:1:TXRS:2951:BLCKS:3:ACCS:3:BQS:1:BDS:4240:TSS:0:UTX:0:VTX:0:CMM:6184266:KDS:126687
2025-10-17 12:24:32.684272   BLOCK_DB+1955. Piece DB usage is 67160456 bytes
2025-10-17 12:24:32.684286      Imported and best 0 (#40154). Has 0 siblings.
2025-10-17 12:24:32.684382   Insterted block with 1 transactions
2025-10-17 12:24:32.684500   Post state changed.
2025-10-17 12:24:32.684520   noteChanged: {chain}
2025-10-17 12:24:32.684583   Total unsafe time so far = 0 seconds
2025-10-17 12:24:32.684674   Reward receiver for block 40154: 9cd7bd826d7fa19f77fa5c94175171457a9e5a04 (index 5)
2025-10-17 12:24:32.684685   Block timestamp: 1759193216
2025-10-17 12:24:32.684735   SWT:3:BFT:12:TQBYTES:CTQ:0:FTQ:0:TQSIZE:CTQ:0:FTQ:0
2025-10-17 12:24:32.684747   Successfully imported 1 of 1 transactions
[2025-10-17 12:24:32.685] [37:main] [info] 40154:BLOCK_COMMITED: PRPSR:6:BID: 40155:ROOT:78508850362728004614307455922103931381787933991838674309263303259211443085799:HASH:6edeecb3:BLOCK_TXS:1:DMSG:0:TPRPS:
6402:MPRPS:0:RPRPS:0:TXS:4541:TXLS:6402:MGS:0:INSTS:0:BPS:0:HDRS:2:SOCK:1:FDS:364:PRT:0:BTA:43849871:BSA:0:TPS:0:LWT:0:LRT:0:LWC:120461:LRC:120541:STAMP:1759193217.873
2025-10-17 12:24:32.694262   createBlock ID = #40155
2025-10-17 12:24:32.694302   STATE ROOT FOR BLOCK: 40154 ad926f427d00a4f42b2ef074cf5c84dcfa952858cde894290aa537fd25ca21e7
2025-10-17 12:24:32.694319   Arrived txn: 41093bc9466fadb1a0c04462fd1e1fc010a36a31a7280e7b001b1a815cb28359
2025-10-17 12:24:32.694567   Paying 9.714 finney from sender for gas (647637 gas at 15 Gwei)
2025-10-17 12:24:32.698041   storageUsed = 483020592
2025-10-17 12:24:32.698544   storageUsed = 483022130
2025-10-17 12:24:32.698603   storageUsed = 101
2025-10-17 12:24:32.699615   Post state changed.
2025-10-17 12:24:32.699633   Processed 1 transactions in 5.159(true)
2025-10-17 12:24:32.699643   HSCT: 2
2025-10-17 12:24:32.699647   Rejigging seal engine...
2025-10-17 12:24:32.699652   Starting to seal block #40155
2025-10-17 12:24:32.699730   Post-reward stateRoot: is not calculated in Skale state
2025-10-17 12:24:32.699738   --- Cache ---
2025-10-17 12:24:32.699765   Block sealed #40155 (#3069cb4d…)
2025-10-17 12:24:32.699784   Block stats:BN:40154:BTS:1759193216:TXS:3:HDRS:12:LOGS:3521:SENGS:1:TXRS:2952:BLCKS:3:ACCS:3:BQS:1:BDS:4241:TSS:0:UTX:0:VTX:0:CMM:6184266:KDS:126692
2025-10-17 12:24:32.699877   BLOCK_DB+1960. Piece DB usage is 67162416 bytes
2025-10-17 12:24:32.699885      Imported and best 0 (#40155). Has 0 siblings.
2025-10-17 12:24:32.699983   Insterted block with 1 transactions
2025-10-17 12:24:32.700091   Post state changed.
2025-10-17 12:24:32.700108   noteChanged: {chain}
2025-10-17 12:24:32.700118   Total unsafe time so far = 0 seconds
2025-10-17 12:24:32.700182   Reward receiver for block 40155: 4581a067d32e2a1c6a0c548769204ed69c323500 (index 6)
2025-10-17 12:24:32.700193   Block timestamp: 1759193217
2025-10-17 12:24:32.700239   SWT:5:BFT:15:TQBYTES:CTQ:0:FTQ:0:TQSIZE:CTQ:0:FTQ:0
2025-10-17 12:24:32.700251   Successfully imported 1 of 1 transactions
[2025-10-17 12:24:32.700] [37:main] [info] 40155:CATCHUP_PROCESSED_BLOCKS:COUNT:6402:DTM:47860:PTM:90506:LTM:0
[2025-10-17 12:24:32.700] [37:main] [info] 40155:CATCHUP_PROCESSED_BLOCKS:COUNT:6402:DTM:47860:PTM:90506:LTM:0
[2025-10-17 12:24:32.800] [37:catchup] [debug] 40155:Catchupc success
[2025-10-17 12:24:32.826] [37:catchup] [debug] 40155:Catchupc step 0: requesting blocks after 40155
[2025-10-17 12:24:32.898] [37:catchup] [debug] 40155:Catchupc step 1: wrote catchup request
[2025-10-17 12:24:33.294] [37:catchup] [debug] 40155:Catchupc step 2: read catchup response requestHeader
[2025-10-17 12:24:35.092] [37:main] [error] 40155:Could not parse BITE transaction: in verifyAndDecryptTransactionList: BiteDataField:Check failed::(uint64_t) _currentEpochId == epoch /home/s5/actions-runne
r-3/_work/skaled/skaled/libconsensus/bite/BiteDataField.cpp:103: Incorrectly formatted BITE transaction: wrong epochId
[2025-10-17 12:24:35.092] [37:main] [error] 40155:Successfully deserialized 0 blocks, got exception on block 40156
[2025-10-17 12:24:35.092] [37:catchup] [error] 40155:Could not deserialize blocks
[2025-10-17 12:24:35.096] [37:catchup] [debug] 40155:Catchupc step 3: got missing blocks:0
[2025-10-17 12:24:35.096] [37:catchup] [debug] 40155:Catchupc success
[2025-10-17 12:24:40.096] [37:catchup] [debug] 40155:Catchupc step 0: requesting blocks after 40155
[2025-10-17 12:24:40.178] [37:catchup] [debug] 40155:Catchupc step 1: wrote catchup request
[2025-10-17 12:24:40.611] [37:catchup] [debug] 40155:Catchupc step 2: read catchup response requestHeader
[2025-10-17 12:24:42.585] [37:main] [error] 40155:Could not parse BITE transaction: in verifyAndDecryptTransactionList: BiteDataField:Check failed::(uint64_t) _currentEpochId == epoch /home/s5/actions-runner-3/_work/skaled/skaled/libconsensus/bite/BiteDataField.cpp:103: Incorrectly formatted BITE transaction: wrong epochId
[2025-10-17 12:24:42.586] [37:main] [error] 40155:Successfully deserialized 0 blocks, got exception on block 40156
[2025-10-17 12:24:42.586] [37:catchup] [error] 40155:Could not deserialize blocks
[2025-10-17 12:24:42.589] [37:catchup] [debug] 40155:Catchupc step 3: got missing blocks:0
[2025-10-17 12:24:42.589] [37:catchup] [debug] 40155:Catchupc success
[2025-10-17 12:24:47.590] [37:catchup] [debug] 40155:Catchupc step 0: requesting blocks after 40155
[2025-10-17 12:24:47.599] [37:catchup] [debug] 40155:Catchupc step 1: wrote catchup request
[2025-10-17 12:24:48.170] [37:catchup] [debug] 40155:Catchupc step 2: read catchup response requestHeader
[2025-10-17 12:24:48.408] [37:main] [error] 40155:Could not parse BITE transaction: in verifyAndDecryptTransactionList: BiteDataField:Check failed::(uint64_t) _currentEpochId == epoch /home/s5/actions-runner-3/_work/skaled/skaled/libconsensus/bite/BiteDataField.cpp:103: Incorrectly formatted BITE transaction: wrong epochId
[2025-10-17 12:24:48.408] [37:main] [error] 40155:Successfully deserialized 0 blocks, got exception on block 40156
[2025-10-17 12:24:48.408] [37:catchup] [error] 40155:Could not deserialize blocks
[2025-10-17 12:24:48.412] [37:catchup] [debug] 40155:Catchupc step 3: got missing blocks:0
[2025-10-17 12:24:48.412] [37:catchup] [debug] 40155:Catchupc success
[2025-10-17 12:24:53.413] [37:catchup] [debug] 40155:Catchupc step 0: requesting blocks after 40155
[2025-10-17 12:24:53.425] [37:catchup] [debug] 40155:Catchupc step 1: wrote catchup request
[2025-10-17 12:24:53.748] [37:catchup] [debug] 40155:Catchupc step 2: read catchup response requestHeader
[2025-10-17 12:24:54.059] [37:main] [error] 40155:Could not parse BITE transaction: in verifyAndDecryptTransactionList: BiteDataField:Check failed::(uint64_t) _currentEpochId == epoch /home/s5/actions-runner-3/_work/skaled/skaled/libconsensus/bite/BiteDataField.cpp:103: Incorrectly formatted BITE transaction: wrong epochId
[2025-10-17 12:24:54.059] [37:main] [error] 40155:Successfully deserialized 0 blocks, got exception on block 40156
[2025-10-17 12:24:54.059] [37:catchup] [error] 40155:Could not deserialize blocks
[2025-10-17 12:24:54.063] [37:catchup] [debug] 40155:Catchupc step 3: got missing blocks:0
[2025-10-17 12:24:54.063] [37:catchup] [debug] 40155:Catchupc success
[2025-10-17 12:24:59.063] [37:catchup] [debug] 40155:Catchupc step 0: requesting blocks after 40155
[2025-10-17 12:24:59.076] [37:catchup] [debug] 40155:Catchupc step 1: wrote catchup request


```

### PR DESCRIPTION
**Pull request by badrogger**
## Description
Problem:
https://github.com/skalenetwork/skaled/issues/2305
During catchup epochId was not incremented. 

## Changes
- Updating group execution is moved from Client::importTransactionsAsBlock to SkaleHost::createBlock (`syncNodeGroup` method). 
- Updating historic group index also moved to SkaleHost::createBlock (`syncNodeGroup` method).
- Setting epochId added to `syncNodeGroup` method

## Tests

- Added unit test 
- Tested on the testnet

## Performance Impact

- No performance related changes are made. setEpochId call is executed only during processing committee rotation block boundaries.

### CODE REVIEW

**Review by kladkogex — DISMISSED** [review]

**Review by olehnikolaiev — DISMISSED** [review]

File: libethereum/Client.cpp [hunk 1]
```diff
@@ -1438,16 +1443,21 @@ void Client::initHistoricGroupIndex() {
     historicGroupIndex = std::distance( nodeGroups.begin(), it );
 }
 
-void Client::updateHistoricGroupIndex() {
+bool Client::updateHistoricGroupIndex() {
```
Comment (kladkogex) [inline libethereum/Client.cpp:1446]: You do not really need updated variable 

This can be simplified to 

Image

File: libethereum/SkaleHost.cpp [hunk 2]
```diff
@@ -802,6 +803,17 @@ void SkaleHost::handleConsensusUpdate() const {
...
+void SkaleHost::syncNodeGroups() {
+    bool isHistoricGroupIndexUpdated = false;
+    if ( m_client.chainParams().getNodeGroups().size() > 0 ) {
+        isHistoricGroupIndexUpdated = m_client.updateHistoricGroupIndex();
+    }
+    bool isGroupUpdated = m_client.updateGroupIfNeeded();
+    if ( isHistoricGroupIndexUpdated || isGroupUpdated ) {
+        runCommitteeRotationForConsensus();
+    }
+}
```
Comment (kladkogex) [inline libethereum/SkaleHost.cpp:810]: This can be simplified to 

Image

Comment (badrogger) [reply libethereum/SkaleHost.cpp]: Updated. We still need to call updateGroupIfNeeded regardless of updateHistoricGroupIndex result.

**Review by kladkogex — APPROVED** [review]

**Review by olehnikolaiev — APPROVED** [review]
