### PR TITLE
2300 No balance transfer after self destruct

### LINKED ISSUE #2300: Disable SELFDESTRUCT transfer functionality
The SELFDESTRUCT opcode currently allows contracts to send remaining Ether to a specified address upon destruction. This behavior can be exploited for unexpected or unauthorized fund transfers. To mitigate this risk, for FAIR the SELFDESTRUCT functionality should be modified so that it does not transfer any funds to any account during contract self-destruction.

### PR DESCRIPTION
**Pull request by badrogger**
## Problem

The SELFDESTRUCT opcode currently allows contracts to send remaining Ether to a specified address upon destruction. This behavior can be exploited for unexpected or unauthorized fund transfers. 

## Changes

For FAIR build sending balance to specified target after self destruct is disabled. 

## Tests

- Tested on local setup.

## Performance Impact

- No performance related changes were introduced.

## Contract example
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

contract Game {
    address owner_addr;
    address[] participants;
    uint participatorID = 0;

    constructor() {
        owner_addr = msg.sender;
    }

    receive() external payable {
        if (msg.value != 1 ether) revert();

        participants.push(msg.sender);
        participatorID++;

        if (address(this).balance >= 10 ether) getWinner();
    }

    function getWinner() internal {
        uint random = uint(blockhash(block.number - 1)) % participants.length;
        payable(participants[random]).transfer(9 ether);

        // Reset for next round
        delete participants;
        participatorID = 0;
    }

    modifier onlyOwner() {
        require(msg.sender == owner_addr);
        _;
    }

    function selfDestruct(address addr) public onlyOwner {
        selfdestruct(payable(addr));
    }
}
```

## Steps to test

1. Deploy contract that has self destruct transaction.
2. Fund contract address.
3. Destroy the transaction using selfDestruct(address a).
4. Balance of address a should not change.

### CODE REVIEW

**Review by DmytroNazarenko — COMMENTED** [review]
Let's run sync node for FAIR Testnet with this version to be sure there is no need to add patch timestamp

File: libethereum/ExtVM.cpp [hunk 1]
```diff
@@ -169,14 +169,16 @@ CreateResult ExtVM::create( u256 _endowment, u256& io_gas, bytesConstRef _code,
...
+void ExtVM::suicide( [[maybe_unused]] Address _a ) {
     // Why transfer is not used here? That caused a consensus issue before (see Quirk #2 in
     // http://martin.swende.se/blog/Ethereum_quirks_and_vulns.html). There is one test case
     // witnessing the current consensus
     // 'GeneralStateTests/stSystemOperationsTest/suicideSendEtherPostDeath.json'.
+#ifndef FAIR
     m_s.addBalance( _a, m_s.balance( myAddress ) );
     m_s.setBalance( myAddress, 0 );
     ExtVMFace::suicide( _a );
+#endif
```
Comment (DmytroNazarenko) [inline libethereum/ExtVM.cpp]: The same ifdef should be for historic node in libhistoric/AlethExtVM.cpp

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]
`#ifdef FAIR` that handles suicides in `Executive::finalize()` should be removed

File: libhistoric/AlethExtVM.cpp [hunk 2]
```diff
@@ -161,14 +164,22 @@ CreateResult AlethExtVM::create( u256 _endowment, u256& io_gas, bytesConstRef _c
...
 }
 
-void AlethExtVM::suicide( dev::Address _a ) {
+void AlethExtVM::suicide( [[maybe_unused]] dev::Address _a ) {
     // Why transfer is not used here? That caused a consensus issue before (see Quirk #2 in
     // http://martin.swende.se/blog/Ethereum_quirks_and_vulns.html). There is one test case
     // witnessing the current consensus
     // 'GeneralStateTests/stSystemOperationsTest/suicideSendEtherPostDeath.json'.
+#ifdef FAIR
+    if ( !DisableSelfDestructPatch::isEnabledInWorkingBlock() ) {
```
Comment (olehnikolaiev) [inline libhistoric/AlethExtVM.cpp]: if a historic call is executed, `isEnabledInWorkingBlock` returns patch status for current block on a node, not the status for historic block

**Review by DmytroNazarenko — APPROVED** [review]

**Review by olehnikolaiev — APPROVED** [review]
