### PR TITLE
SKALED-1812 Use _enablePrivilegedApis in jsonrpc's Debug

### LINKED ISSUE #1812: Broken JsonRpcSuite/doDbCompactionDebugCall test in skaled
In v3.17.2 JsonRpcSuite/doDbCompactionDebugCall fails with the message:
```
fatal error: in "JsonRpcSuite/doDbCompactionDebugCall": jsonrpc::JsonRpcException: This API call is not enabled
```

### PR DESCRIPTION
**Pull request by dimalit**
Tests' fixture now uses _enablePrivilegedApis=true in Debug class.
Before that, test was failing because of disabled privileged access.

### CODE REVIEW

**Review by DmytroNazarenko — DISMISSED** [review]

File: test/unittests/libweb3jsonrpc/jsonrpc.cpp [hunk 1]
```diff
@@ -346,7 +346,7 @@ struct JsonRpcFixture : public TestOutputHelperFixture {
         rpcServer.reset( new FullServer( ethFace , new rpc::Net( chainParams ),
             new rpc::Web3( /*web3->clientVersion()*/ ),  // TODO Add real version?
             new rpc::AdminEth( *client, *gasPricer, keyManager, *sessionManager.get() ),
-            /*new rpc::AdminNet(*web3, *sessionManager), */ new rpc::Debug( *client ),
+          /*new rpc::AdminNet(*web3, *sessionManager), */ new rpc::Debug( *client, nullptr, "", true),
```
Comment (kladkogex) [inline test/unittests/libweb3jsonrpc/jsonrpc.cpp]: Please remove dead code

**Review by kladkogex — APPROVED** [review]
