### PR TITLE
Fix state root mismatch error on 4.0.0

### LINKED ISSUE #2085: Fix state root mismatch in 4.0
Since we optimized the way partial receipts are handled in 2.0, looks like this caused state root mismatch.

Fix  the mismatch,  also add a test for it.

### PR DESCRIPTION
**Pull request by badrogger**
## Description
Keep the old way of saving partial receipts before `ClearPartialReceiptsPatchTimestamp`

## Tests
- Added unit tests
- Tested on local network by launching archive node with `syncFromCatchup=True` 

## Performance Impact
- Additional commit to DB added per block. No performance changes expected.

### CODE REVIEW

File: libskale/State.cpp [hunk 1]
```diff
@@ -321,6 +321,39 @@ void State::safeRemoveAllPartialTransactionReceipts() {
...
+
+
+dev::eth::TransactionReceipts State::safeLegacyPartialTransactionReceipts() {
+    dev::eth::TransactionReceipts legacyPartialTransactionReceipts;
+    if ( m_db_ptr ) {
+        auto rawTransactionReceipts = m_db_ptr->getLegacyPartialTransactionReceipts();
+        if ( !rawTransactionReceipts.empty() ) {
+            dev::RLP rlp( rawTransactionReceipts );
+            dev::eth::BlockReceipts blockReceipts( rlp );
+            legacyPartialTransactionReceipts.insert( legacyPartialTransactionReceipts.end(),
```
Comment (olehnikolaiev) [inline libskale/State.cpp]: you can simply do `return blockReceipts.receipts;`

File: libethereum/Block.cpp [hunk 2]
```diff
@@ -587,6 +591,16 @@ tuple< TransactionReceipts, unsigned > Block::syncEveryone( BlockChain const& _b
 
     LDB_CHECK( receipts.size() >= countBad );
 
+    if ( ClearPartialReceiptsPatch::isEnabledWhen( _timestamp ) ) {
+        // Making sure the old record was removed from the state db
+        m_state.safeRemoveLegacyPartialTransactionReceipts();
```
Comment (olehnikolaiev) [inline libethereum/Block.cpp]: can we optimize this process so that we won't have to try to remove non-existing key? for example, we can check the timestamp of the previous block and compare it with patchTimestamp

**Review by DmytroNazarenko — DISMISSED** [review]

File: libethereum/Block.cpp (hunk 2 above)
Comment (badrogger) [reply libethereum/Block.cpp]: addressed

File: libskale/State.cpp (hunk 1 above)
Comment (badrogger) [reply libskale/State.cpp]: addressed

**Review by olehnikolaiev — APPROVED** [review]

**Review by DmytroNazarenko — APPROVED** [review]
