### PR TITLE
2258 Zero snapshot downloading fix

### LINKED ISSUE #2258: Skaled downloads 0 snaphsot only with download-snapshot option in cmdline
**Describe the bug**
Indexer and Historic node initially running from the catchup and the 0 block can have a different state, as every admin version generates 0 block with a unique configuration 
Downloading 0-block from core nodes is much preferable to avoid unexpected changes in the genesis block
 
**Preconditions**
Fair chain 4 active nodes in the committee 
2 whitelisted passive nodes 

**Version**
skalenetwork/schain:4.1.0-develop.43.1-fair-relwithdebinfo
skalenetwork/schain:4.1.0-develop.43.1-fair-relwithdebinfo-historic

**To Reproduce**
1. Init indexer or historic node from catchup - [Node-CLI -passive-node-commands)](https://github.com/skalenetwork/node-cli/tree/fair?tab=readme-ov-file#passive-node-commands)
2. Wait for skaled initialization
3. Check skaled logs 

**Expected behavior**
Skaled should download a snapshot with 0 block number, even though it has started from the catchup 
 
**Actual state:**
Skaled generates his own 0 block, which breaks compatibility for L1 and L2 skaled, as the 0 block can be regenerated for each generation of L2 chains 

```
[2025-08-20 14:38:45.296] [6:main] [debug] 0:Got current node id 1 for index 2 and timestamp 1755598286
[2025-08-20 14:38:45.296] [6:consensus] [debug] 0:Share's signer index is 3
[2025-08-20 14:38:45.296] [6:main] [debug] 0:Looking for historic nodeId by index 3 for timestamp 1755598286 to verify a block came through catchup
[2025-08-20 14:38:45.296] [6:main] [debug] 0:Got current node id 4 for index 3 and timestamp 1755598286
[2025-08-20 14:38:45.296] [6:main] [debug] 0:Looking for BLS public key for timestamp 1755598286 to verify a block came through catchup
[2025-08-20 14:38:45.296] [6:main] [debug] 0:Got current BLS public key 19426335780201625832416916049430152553099025858482283611441804377998893893622:16973097888462061439311758385584746907662637339298366236
922343733539886201484:10888796729726550622686591332523770108243619668785279673506353814306794866682:9550119918850033931382769651258453369770434099381880633907976935047835349163:
[2025-08-20 14:38:45.302] [6:catchup] [info] 0:CATCHUP_GOT_BLOCKS:COUNT:32887:STARTBLOCK:1:FROM_NODE:140.82.2.89
[2025-08-20 14:38:45.308] [6:catchup] [debug] 0:Catchupc step 3: got missing blocks:32887
[2025-08-20 14:38:45.309] [6:main] [info] 0:BLOCK_COMMITED: PRPSR:0:BID: 1:ROOT:0:HASH:a1cbca1e:BLOCK_TXS:0:DMSG:0:TPRPS:32887:MPRPS:0:RPRPS:0:TXS:50617:TXLS:32887:MGS:0:INSTS:0:BPS:0:HDRS:2:SOCK:1:FDS:339:
PRT:0:BTA:0:BSA:0:TPS:0:LWT:0:LRT:0:LWC:2:LRC:4:STAMP:0.1
2025-08-20 14:38:45.318190   createBlock ID = #1
2025-08-20 14:38:45.318467   DOING SNAPSHOT: 0
2025-08-20 14:38:45.393608   "/data_dir/snapshots/0/28e07f34/12041/state" hash is: b8f962b444647e92030c6011dbc365b26bae0fa3c13e07894fee527f07f96090
2025-08-20 14:38:45.401390   "/data_dir/snapshots/0/28e07f34/blocks_and_extras/0.db" hash is: fe3e2b08fc0151b09bad2558af3c5e61591ca7ef6332342b51269a924938a7eb
2025-08-20 14:38:45.408040   "/data_dir/snapshots/0/28e07f34/blocks_and_extras/1.db" hash is: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2025-08-20 14:38:45.415081   "/data_dir/snapshots/0/28e07f34/blocks_and_extras/2.db" hash is: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2025-08-20 14:38:45.422332   "/data_dir/snapshots/0/28e07f34/blocks_and_extras/3.db" hash is: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2025-08-20 14:38:45.428575   "/data_dir/snapshots/0/28e07f34/blocks_and_extras/4.db" hash is: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2025-08-20 14:38:45.464832   Computed hash for snapshot 0: #3c3522c0…
2025-08-20 14:38:45.464921   Latest snapshots init: 0 0 -> -1
2025-08-20 14:38:45.464943   Init last snapshot creation time: 0
2025-08-20 14:38:45.465424   Block sealed #1 (#5d673b1b…)
2025-08-20 14:38:45.465633   Block stats:BN:0:BTS:0:TXS:0:HDRS:12:LOGS:40:SENGS:1:TXRS:0:BLCKS:3:ACCS:5:BQS:1:BDS:36:TSS:0:UTX:0:VTX:0:CMM:0:KDS:0:RAM:289736:CPU:47.5461
2025-08-20 14:38:45.466074   noteChanged: {chain}
2025-08-20 14:38:45.466103   Winner for block 1: 0000000000000000000000000000000000000000 (index 0)
2025-08-20 14:38:45.466176   SWT:148:TQBYTES:CTQ:0:FTQ:0:TQSIZE:CTQ:0:FTQ:0
2025-08-20 14:38:45.466187   Successfully imported 0 of 0 transactions
[2025-08-20 14:38:45.466] [6:main] [info] 1:BLOCK_COMMITED: PRPSR:3:BID: 2:ROOT:46320509353513273106582423493727320152202237096314791991810382902766530930981:HASH:b7ce6866:BLOCK_TXS:0:DMSG:0:TPRPS:32887:MPRPS:0:RPRPS:0:TXS:50617:TXLS:32887:MGS:0:INSTS:0:BPS:0:HDRS:2:SOCK:1:FDS:339:PRT:0:BTA:1755700725466:BSA:0:TPS:0:LWT:0:LRT:0:LWC:5:LRC:4:STAMP:1755272671.42
2025-08-20 14:38:45.473415   createBlock ID = #2
2025-08-20 14:38:45.473451   Last snapshot creation time: 0
2025-08-20 14:38:45.473644   Block sealed #2 (#c3611b29…)
2025-08-20 14:38:45.473657   Block stats:BN:1:BTS:0:TXS:0:HDRS:12:LOGS:40:SENGS:1:TXRS:0:BLCKS:3:ACCS:5:BQS:1:BDS:36:TSS:0:UTX:0:VTX:0:CMM:9252:KDS:0
2025-08-20 14:38:45.473788   noteChanged: {chain}

```

### PR DESCRIPTION
**Pull request by badrogger**
## Description

- Fixed condition to download zero snapshot
- Adding missing zero snapshot restoration

## Tests

- Tested on local network

## Performance Impact

- No performance related changes were made

### CODE REVIEW

File: skaled/main.cpp [hunk 1]
```diff
@@ -1818,7 +1827,7 @@ int main( int argc, char** argv ) {
         }  // if --download-snapshot
 
         // download 0 snapshot if needed
-        if ( chainParams->isSyncNode() && !dataDirEmpty ) {
+        if ( chainParams->isSyncNode() && dataDirEmpty ) {
```
Comment (olehnikolaiev) [inline skaled/main.cpp]: I think we can keep only one of `dataDirEmpty` and `bc.number() == 0` conditions

**Review by olehnikolaiev — DISMISSED** [review]

File: skaled/main.cpp [hunk 2]
```diff
@@ -726,6 +731,10 @@ void doSnapshotDownload( const std::shared_ptr< ChainParams >& chainParams,
 #endif
         downloadAndProccessSnapshot(
             snapshotManager, *chainParams, urlToDownloadSnapshotFrom, false );
+        if ( zeroSnapshotOnly ) {
+            // Restoring here since we do not restore it during latest snapshot download
+            snapshotManager->restoreSnapshot( 0 );
+        }
```
Comment (DmytroNazarenko) [inline skaled/main.cpp:737]: Do we need to restore the 0 snapshot in cases other than syncing from catchup?

**Review by DmytroNazarenko — COMMENTED** [review]
Do we have any tests for 0-snapshot downloading?

File: skaled/main.cpp [hunk 3]
```diff
@@ -1818,14 +1827,11 @@ int main( int argc, char** argv ) {
...
         // download 0 snapshot if needed
-        if ( chainParams->isSyncNode() && !dataDirEmpty ) {
-            auto bc = BlockChain( chainParams, getDataDir() );
-            if ( bc.number() == 0 ) {
-                // zeroSnapshotOnly is set to true
-                if ( chainParams->isSyncFromCatchupEnabled() && !downloadSnapshotFlag ) {
-                    doSnapshotDownload( chainParams, statusAndControl, urlToDownloadSnapshotFrom,
-                        snapshotManager, sharedSpace, true );
-                }
+        if ( chainParams->isSyncNode() && dataDirEmpty ) {
```
Comment (DmytroNazarenko) [inline skaled/main.cpp]: Isn't it sufficient to just check chainParams->isSyncFromCatchupEnabled() && dataDirEmpty && !downloadSnapshotFlag?

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]
The last commit includes 2k lines of changes, which looks like a linter was applied. Please revert this and keep only the intended changes

File: skaled/main.cpp [hunk 4]
```diff
@@ -1818,15 +1827,10 @@ int main( int argc, char** argv ) {
...
-        if ( chainParams->isSyncNode() && !dataDirEmpty ) {
-            auto bc = BlockChain( chainParams, getDataDir() );
-            if ( bc.number() == 0 ) {
-                // zeroSnapshotOnly is set to true
-                if ( chainParams->isSyncFromCatchupEnabled() && !downloadSnapshotFlag ) {
-                    doSnapshotDownload( chainParams, statusAndControl, urlToDownloadSnapshotFrom,
-                        snapshotManager, sharedSpace, true );
-                }
-            }
+        if ( chainParams->isSyncFromCatchupEnabled() && dataDirEmpty && !downloadSnapshotFlag ) {
```
Comment (DmytroNazarenko) [inline skaled/main.cpp:1830]: What is expected behaviour for node with both syncFromCatchup and downloadSnapshot options?

Comment (badrogger) [reply skaled/main.cpp:1830]: snapshot should be downloaded

**Review by DmytroNazarenko — APPROVED** [review]

**Review by olehnikolaiev — APPROVED** [review]
