### PR TITLE
Bug/2280 wrong group index on start

### LINKED ISSUE #2280: skaled starts with wrong group index if exits right after rotation
if skaled exits right after rotation (committee or node) is completed, then on start it initializes with wrong group index. this leads to incorrect behavior and blockchain divergence 

this bug is the reason why https://github.com/skalenetwork/skale-consensus/issues/935 occured

### PR DESCRIPTION
**Pull request by olehnikolaiev**
fixes https://github.com/skalenetwork/skaled/issues/2280

if skaled exited right after the rotation was completed, then on startup it initialised with wrong group index. 

for L2 the bug was silent because the scenario to reproduce it is hard to make - the fix requires patch timestamp to make sure the existing chains won't be affected
for FAIR patch timestamp will be enabled by default

tested on local machine - bug was present for both L2 and FAIR builds

### CODE REVIEW

**Review by kladkogex — DISMISSED** [review]

File: libethereum/SchainPatch.h [hunk 1]
```diff
@@ -177,4 +177,11 @@ DEFINE_SIMPLE_PATCH( InvalidTransactionFormatPatch );
  */
 DEFINE_SIMPLE_PATCH( CurrentBlockRandomPatch );
 
+/*
+ * Context: fix group index initialization on startup
+ * if skaled exits after the first block after rotation timestamp
+ * then it starts again and initializes with wrong group index
```
Comment (DmytroNazarenko) [inline libethereum/SchainPatch.h:183]: Add version please

**Review by badrogger — DISMISSED** [review]

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]

**Review by DmytroNazarenko — APPROVED** [review]
