### PR TITLE
#2259 fix snapshot hash calculation

### LINKED ISSUE #2259: Skaled on historic node crashes without snapshot_hash.txt file
**Describe the bug**
Skaled is doing a snapshot every snapshot interval and calculates the snapshot hash during this period -1hour on Devnet and QAnet, 24 hours on  Testnet and Mainnet. Every snapshot hash is needed for the state root for the future blocks 
Reproducible only on historic nodes 

**Preconditions**
Fair chain 4 active nodes in committee - at least 3 snapshots are created
1 passive historic node whitelisted on the Fair manager
1-hour snapshot interval

**Versions:**
skalenetwork/schain:4.1.0-develop.43.1-fair-relwithdebinfo-historic

**To Reproduce**
1. Setup the passive historic node from the catchup [Node-CLI -passive-node-commands)](https://github.com/skalenetwork/node-cli/tree/fair?tab=readme-ov-file#passive-node-commands)
2. Wait until skaled on historic nodes starts catching up with the new block 
3. Stop the fair admin to avoid restarting the skaled container 
4. Check the skaled logs for the next  snapshots until the historic node is synced with the committee nodes 

**Expected behavior**
Skaled on the historic node should wait for the snapshot hash calculation during the catch-up procedure, and keep alive without any crashes

**Actual state:**
Skaled doesn’t wait for the snapshot hash of the previous snapshot to be generated and crashes with a state root mismatch error. 

**Logs:**

[snapshot_calculation_failed.txt](https://github.com/user-attachments/files/21901645/snapshot_calculation_failed.txt)

```

25-08-20 12:08:49.133953   Block sealed #14 (#6c579994…)
2025-08-20 12:08:49.133961   Block stats:BN:13:BTS:1755261401:TXS:0:HDRS:12:LOGS:42:SENGS:1:TXRS:0:BLCKS:3:ACCS:5:BQS:1:BDS:51:TSS:0:UTX:0:VTX:0:CMM:10086:KDS:0
2025-08-20 12:08:49.134124   noteChanged: {chain}
2025-08-20 12:08:49.134137   Winner for block 14: d70467bdf66eeae4f7f0a5f004176a1d9aa69115 (index 3)
2025-08-20 12:08:49.134166   SWT:0:BFT:8:TQBYTES:CTQ:0:FTQ:0:TQSIZE:CTQ:0:FTQ:0
2025-08-20 12:08:49.134170   Successfully imported 0 of 0 transactions
2025-08-20 12:08:49.141241   LEVELDB_OPENED:/data_dir/snapshots/2/blocks_7.db/db.4:TIME_MS:12
2025-08-20 12:08:49.141526   CRITICAL Unexpected character encountered in input. ---  in computeSnapshotHash(). Exiting...
THREADS timer started[2025-08-20 12:08:49.142] [7:main] [info] 15:BLOCK_COMMITED: PRPSR:1:BID: 16:ROOT:46320509353513273106582423493727320152202237096314791991810382902766530930981:HASH:7250ba0b:BLOCK_TXS:0:DMSG:0:TPRPS:37341:MPRPS:0:RPRPS:0:TXS:6443:TXLS:37341:MGS:0:INSTS:0:BPS:0:HDRS:2:SOCK:1:FDS:348:PRT:0:BTA:125406552081:BSA:0:TPS:0:LWT:0:LRT:0:LWC:44:LRC:31:STAMP:1755261468.720

Internal exit initiated. Signal -1. Unknown signal type.


2025-08-20 12:08:49.142418   createBlock ID = #15
2025-08-20 12:08:49.142519   storageUsed = 4719
2025-08-20 12:08:49.142531   storageUsed = 98
2025-08-20 12:08:49.142568   HSCT: 0
2025-08-20 12:08:49.142588   Block sealed #15 (#9655084a…)
2025-08-20 12:08:49.142595   Block stats:BN:14:BTS:1755261435:TXS:0:HDRS:12:LOGS:42:SENGS:1:TXRS:0:BLCKS:3:ACCS:5:BQS:1:BDS:52:TSS:0:UTX:0:VTX:0:CMM:10086:KDS:0
2025-08-20 12:08:49.142705   noteChanged: {chain}
2025-08-20 12:08:49.142717   Winner for block 15: 5969aed93cd25794e832709e0167016f839d6ff5 (index 4)
2025-08-20 12:08:49.141543   
  /skaled/skaled : ()+0x2289b0 [0x55e1ee4c09b0]
  /lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0xdc253 [0x7fce5db38253]
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x94ac3 [0x7fce5d7beac3]
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x126850 [0x7fce5d850850]

2025-08-20 12:08:49.142758   SWT:0:BFT:8:TQBYTES:CTQ:0:FTQ:0:TQSIZE:CTQ:0:FTQ:0
2025-08-20 12:08:49.142762   Successfully imported 0 of 0 transactions
2025-08-20 12:08:49.148553   createBlock ID = #16
2025-08-20 12:08:49.148645   storageUsed = 5068
2025-08-20 12:08:49.148664   storageUsed = 98

...
2025-08-20 12:08:49.689798   SWT:0:BFT:5:TQBYTES:CTQ:0:FTQ:0:TQSIZE:CTQ:0:FTQ:0
2025-08-20 12:08:49.689805   Successfully imported 0 of 0 transactions
[2025-08-20 12:08:49.689] [7:main] [info] 105:BLOCK_COMMITED: PRPSR:3:BID: 106:ROOT:46320509353513273106582423493727320152202237096314791991810382902766530930981:HASH:f0956471:BLOCK_TXS:0:DMSG:0:TPRPS:37341:MPRPS:0:RPRPS:0:TXS:6443:TXLS:37341:MGS:0:INSTS:0:BPS:0:HDRS:2:SOCK:1:FDS:287:PRT:0:BTA:16881651247:BSA:0:TPS:0:LWT:0:LRT:0:LWC:314:LRC:211:STAMP:1755262789.189
2025-08-20 12:08:49.695268   createBlock ID = #106
2025-08-20 12:08:49.695362   storageUsed = 38314
2025-08-20 12:08:49.695382   storageUsed = 99
2025-08-20 12:08:49.695423   HSCT: 0
2025-08-20 12:08:49.695448   Block sealed #106 (#a3e70d86…)
2025-08-20 12:08:49.695460   Block stats:BN:105:BTS:1755262787:TXS:0:HDRS:12:LOGS:42:SENGS:1:TXRS:0:BLCKS:3:ACCS:5:BQS:1:BDS:143:TSS:0:UTX:0:VTX:0:CMM:10086:KDS:0
2025-08-20 12:08:49.695587   noteChanged: {chain}
2025-08-20 12:08:49.695603   Winner for block 106: d70467bdf66eeae4f7f0a5f004176a1d9aa69115 (index 3)
2025-08-20 12:08:49.695645   SWT:0:BFT:5:TQBYTES:CTQ:0:FTQ:0:TQSIZE:CTQ:0:FTQ:0
2025-08-20 12:08:49.695652   Successfully imported 0 of 0 transactions
[2025-08-20 12:08:49.695] [7:main] [info] 106:BLOCK_COMMITED: PRPSR:4:BID: 107:ROOT:46320509353513273106582423493727320152202237096314791991810382902766530930981:HASH:5f142632:BLOCK_TXS:0:DMSG:0:TPRPS:37341:MPRPS:0:RPRPS:0:TXS:6443:TXLS:37341:MGS:0:INSTS:0:BPS:0:HDRS:2:SOCK:1:FDS:287:PRT:0:BTA:16720873616:BSA:0:TPS:0:LWT:0:LRT:0:LWC:317:LRC:213:STAMP:1755262800.473
2025-08-20 12:08:49.701087   createBlock ID = #107
2025-08-20 12:08:49.701115   Last snapshot creation time: 1755261232
2025-08-20 12:08:49.701266   storageUsed = 38810
2025-08-20 12:08:49.701289   storageUsed = 99
2025-08-20 12:08:49.701333   HSCT: 0
2025-08-20 12:08:49.701443   CRITICAL Cannot read /data_dir/snapshots/2/snapshot_hash.txt (in createBlock)
2025-08-20 12:08:49.701452   
  /skaled/skaled : ()+0x226be2 [0x55e1ee4bebe2]
  /skaled/skaled : ()+0x523f0e [0x55e1ee7bbf0e]
  /skaled/skaled : ()+0x86abcd [0x55e1eeb02bcd]
  /skaled/skaled : ()+0x86fd5c [0x55e1eeb07d5c]
  /skaled/skaled : ()+0x871205 [0x55e1eeb09205]
  /skaled/skaled : ()+0x853d15 [0x55e1eeaebd15]
  /skaled/skaled : ()+0x854874 [0x55e1eeaec874]
  /lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0xdc253 [0x7fce5db38253]
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x94ac3 [0x7fce5d7beac3]
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x126850 [0x7fce5d850850]
[2025-08-20 12:08:49.702] [7:main] [info] 107:BLOCK_COMMITED: PRPSR:1:BID: 108:ROOT:17396970439090270977292459408589803874658150309419252089855549923853206841441:HASH:905908e6:BLOCK_TXS:0:DMSG:0:TPRPS:37341:MPRPS:0:RPRPS:0:TXS:6443:TXLS:37341:MGS:0:INSTS:0:BPS:0:HDRS:2:SOCK:1:FDS:287:PRT:0:BTA:16563129525:BSA:0:TPS:0:LWT:0:LRT:0:LWC:320:LRC:215:STAMP:1755262821.853
SELF-KILL: Will sleep 270 seconds before force exit...0.000180571 THREADS 31: +main +main +dPool0 +blockVerifier0 +main +MonitoringLoop +CatchupClient +Client +ZMQbg/Reaper +ZMQbg/IO/0 +ZmqBroadcaster +broadcastFunc +CtchpSrvAg0 +CtchpSrvAg1 +CtchpSrvAg2 +CtchpSrvAg3 +CatchupServer +ain/WS-listener +-0x55e22d7ce460 +HTTPSrvExec0 +HTTPSrvExec1 +HTTPSrvExec2 +HTTPSrvExec3 +HTTPSrvExec4 +HTTPSrvExec5 +HTTPSrvExec6 +HTTPSrvExec7 +HTTPSrvExec8 +HTTPSrvExec9 +IOThreadPool0 +CatchupClient0.10114 THREADS 19: --0x55e22d7ce460 -HTTPSrvExec0 -HTTPSrvExec1 -HTTPSrvExec2 -HTTPSrvExec3 -HTTPSrvExec4 -HTTPSrvExec5 -HTTPSrvExec6 -HTTPSrvExec7 -HTTPSrvExec8 -HTTPSrvExec9 -IOThreadPool0Here is stack trace for your info:
2025-08-20 12:08:49.707503   createBlock ID = #108
2025-08-20 12:08:49.707547   FATAL STATE ROOT MISMATCH ERROR: current state root 46320509353513273106582423493727320152202237096314791991810382902766530930981 is not equal to arrived state root 17396970439090270977292459408589803874658150309419252089855549923853206841441 with block ID #108, /data_dir cleanup is recommended, exiting with code 200...
[2025-08-20 12:08:49.707] [7:consensus] [info] 107:Running exitGracefully method
[2025-08-20 12:08:49.707] [7:consensus] [info] 107:Iterating over nodes
[2025-08-20 12:08:49.707] [7:consensus] [info] 107:Processing a node exit
[2025-08-20 12:08:49.707] [7:main] [info] 107:Set exit on block boundary
[2025-08-20 12:08:49.707] [7:consensus] [info] 107:Consensus exiting: exitGracefully called by skaled
 0# 0x000055E1EEA5935C in /skaled/skaled
 1# 0x000055E1EE7C22A6 in /skaled/skaled
 2# 0x000055E1EE7C2681 in /skaled/skaled
 3# 0x000055E1EE7BBF0E in /skaled/skaled
 4# 0x000055E1EEB02BCD in /skaled/skaled
 5# 0x000055E1EEB07D5C in /skaled/skaled
 6# 0x000055E1EEB09205 in /skaled/skaled
 7# 0x000055E1EEAEBD15 in /skaled/skaled
 8# 0x000055E1EEAEC874 in /skaled/skaled
 9# 0x00007FCE5DB38253 in /lib/x86_64-linux-gnu/libstdc++.so.6
10# start_thread at ./nptl/pthread_create.c:442
11# 0x00007FCE5D850850 at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:83

[2025-08-20 12:08:49.795] [config] [info] Consensus engine exiting: exitGracefullyAsync called by skaled
[2025-08-20 12:08:49.795] [config] [info] exitGracefullyAsync running
[2025-08-20 12:08:49.795] [config] [info] Node exit called
[2025-08-20 12:08:49.795] [config] [info] Node::exit() requested
2025-08-20 12:08:49.795506   Mismatch in block number:SKALED_NUMBER:106:CONSENSUS_NUMBER:108
2025-08-20 12:08:49.795527   Last snapshot creation time: 1755261232
2025-08-20 12:08:49.795662   storageUsed = 198
2025-08-20 12:08:49.795741   HSCT: 0
2025-08-20 12:08:49.795789   CRITICAL Cannot read /data_dir/snapshots/2/snapshot_hash.txt (in createBlock)
2025-08-20 12:08:49.795791   
  /skaled/skaled : ()+0x226be2 [0x55e1ee4bebe2]
  /skaled/skaled : ()+0x523f0e [0x55e1ee7bbf0e]
  /skaled/skaled : ()+0x86abcd [0x55e1eeb02bcd]
  /skaled/skaled : ()+0x86fd5c [0x55e1eeb07d5c]
  /skaled/skaled : ()+0x871205 [0x55e1eeb09205]
  /skaled/skaled : ()+0x853d15 [0x55e1eeaebd15]
  /skaled/skaled : ()+0x854874 [0x55e1eeaec874]
  /lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0xdc253 [0x7fce5db38253]
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x94ac3 [0x7fce5d7beac3]
  /lib/x86_64-linux-gnu/libc.so.6 : ()+0x126850 [0x7fce5d850850]
[2025-08-20 12:08:49.795] [7:main] [info] 107:Exiting on block boundary for block 107
[2025-08-20 12:08:49.795] [7:main] [info] 107:exitImmediately called
[2025-08-20 12:08:49.796] [7:main] [info] 107:Status server stopped
[2025-08-20 12:08:49.796] [7:main] [info] 107:consensus engine exiting: close all sockets called
[2025-08-20 12:08:49.796] [7:main] [info] 107:consensus engine exiting: server conditional vars notified
[2025-08-20 12:08:49.796] [7:main] [info] 107:consensus engine exiting: agent conditional vars notified
[2025-08-20 12:08:49.796] [7:main] [info] 107:consensus engine exiting: catchup socket touched
[2025-08-20 12:08:49.796] [7:main] [info] 107:exitImmediately completed
[2025-08-20 12:08:49.796] [7:main] [info] 107:Consensus exiting: Node:Exit requested

Internal exit requested while already exiting. Signal -1. Unknown signal type.

[2025-08-20 12:08:49.797] [7:main] [info] 107:Consensus exiting: Node:Exit requested
[2025-08-20 12:08:49.797] [7:main] [info] 107:Consensus exiting: Node:Exit requested
[2025-08-20 12:08:49.797] [7:main] [info] 107:Consensus exiting: Node:Exit requested
[2025-08-20 12:08:49.895] [config] [info] Node::exit() will try to exit on block boundary for 30 seconds
[2025-08-20 12:08:49.995] [config] [info] Node exit completed

```

### PR DESCRIPTION
**Pull request by olehnikolaiev**
fixes https://github.com/skalenetwork/skaled/issues/2259

1. fix snapshot hash calculation for FAIR build
2. fix unit test that was broken for a while
3. better error handling during snapshot voting procedure

### CODE REVIEW

**Review by badrogger — DISMISSED** [review]

File: libskale/SnapshotManager.cpp [hunk 1]
```diff
@@ -524,11 +524,15 @@ void SnapshotManager::computeDatabaseHash(
 void SnapshotManager::addLastPriceToHash( unsigned _blockNumber, secp256k1_sha256_t* ctx ) const {
     dev::u256 last_price = 0;
     // manually open DB
+    std::string pricesDbName = "prices_" + chainParams->getSelfNodeId().str() + ".db";
+    auto pricesDbVolumeIt = std::find( coreVolumes.begin(), coreVolumes.end(), pricesDbName );
+    if ( pricesDbVolumeIt == coreVolumes.end() )
+        throw std::runtime_error( "No btrfs module prices_db" );
```
Comment (DmytroNazarenko) [inline libskale/SnapshotManager.cpp:530]: Will this work correctly with already running sync/indexer nodes for SKALE Chains, where the id is taken from another node?

File: libskale/SnapshotManager.cpp [hunk 2]
```diff
@@ -524,11 +524,15 @@ void SnapshotManager::computeDatabaseHash(
...
     boost::filesystem::path prices_path =
-        this->snapshotsDir / std::to_string( _blockNumber ) / coreVolumes[2];
+        this->snapshotsDir / std::to_string( _blockNumber ) / *pricesDbVolumeIt;
     if ( boost::filesystem::exists( prices_path ) ) {
         boost::filesystem::directory_iterator it( prices_path ), end;
```
Comment (DmytroNazarenko) [inline libskale/SnapshotManager.cpp:534]: I suggest using `std::filesystem::directory_iterator` instead, and replacing the while loop with the C++20 alternative:
`for (const auto& entry : std::filesystem::directory_iterator(prices_path)) {`

File: libskale/SnapshotHashAgent.cpp [hunk 3]
```diff
@@ -301,7 +301,7 @@ std::vector< std::string > SnapshotHashAgent::getNodesToDownloadSnapshotFrom(
                                               .convert_to< std::string >();
 
                     auto snapshotData = askNodeForHash( nodeUrl, blockNumber );
```
Comment (DmytroNazarenko) [inline libskale/SnapshotHashAgent.cpp]: Suggest to replace `get<i>` and work with tuples like this to improve code readability:
```
auto [hash, signature, publicKey] = snapshotData;
if ( hash != dev::h256() )
```

**Review by DmytroNazarenko — CHANGES_REQUESTED** [review]

File: libskale/SnapshotManager.cpp (hunk 1 above)
Comment (olehnikolaiev) [reply libskale/SnapshotManager.cpp:530]: yes, the submodule is initialized with the same name in `SnapshotManager` constructor. moreover, the id used to initialized this submodule is also used in other places

File: libskale/SnapshotManager.cpp (hunk 2 above)
Comment (olehnikolaiev) [reply libskale/SnapshotManager.cpp:534]: we use boost::filesystem::iterator everywhere else in the code. the reason is that back when the code was added std::filesystem was still an experimental feature. however, it might be a good idea to keep consistency in terms of libraries / algorithms is used for specific purposes

Comment (DmytroNazarenko) [reply libskale/SnapshotManager.cpp:534]: `std::filesystem` was standardized from Boost. Let's create a ticket to migrate from `boost::filesystem` to `std::filesystem` in skaled, so we can explicitly test the changes, then. It makes code cleaner

**Review by DmytroNazarenko — APPROVED** [review]

**Review by badrogger — APPROVED** [review]
